### ISSUE TITLE
Can't show on sidebar when I have custom menu sections and items

### ISSUE THREAD

**Issue by nadlambino** [ferdiunal/nova-shield#2]
First of all, thanks for this! It's a great package. However, I am can't show this on my sidebar when I have a custom menu sections and items. I am fairly new to nova and I am not sure if this is a nova issue or if there should be a way for this package to be manually display.

**Comment by nadlambino** [comment]
Found the solution. Just have to add it as menu item using path, then add the tools separately

**Comment by ferdiunal** [comment]
First of all, thank you for your kind words and for using the package. While developing the package, I focused on Resources, but based on the issue you've encountered, I realized that further development is needed for custom menus and tools outside of Resources. I will work on improvements for this. Thank you.

**Comment by nadlambino** [comment]
Hey there, thanks for your response. I just have some improvement request, which I think are good to have. I am not sure if this was already available but not just documented, but it would be great if the colour of the active toggle uses the branding colour. Also, if we can make the roles and permissions names a non-developer friendly? I'll try take a look at these when I have free time and try to contribute if I can, but if you're able to implement it, that would also be great. Thanks again!

**Comment by ferdiunal** [comment]
Hi, the toggle part can be done. For permissions, language support (**Nova.__(‘...’)**) feature can be added, I will work on it.
