### ISSUE TITLE
I only see user and shield permissions

### ISSUE THREAD

**Issue by scramatte** [ferdiunal/nova-shield#4]
Hi,

I only see user and shield permissions when I create a new shield resource. What I've missed ?
Moreover do I must still attach user to shield resource  manually?

![imagen](https://github.com/user-attachments/assets/2248ce71-30ee-41fa-881f-4be7d6685fbe)

Regards

**Comment by ferdiunal** [comment]
"I only see user and shield permissions when I create a new shield resource. What I've missed?" Could you provide a bit more detail on this? You can check this test repo for help [ferdiunal/nova-shield-example](https://github.com/ferdiunal/nova-shield-example)

"Moreover do I must still attach user to shield resource manually?"

Yes, the package currently only handles roles and permissions management. It doesn't provide a component for users, so you'll need to attach them manually. This feature might be added in the future.

**Comment by scramatte** [comment]
Hi, 

I've added  "use PermissionAuthorizable" to my app/Nova/Resource.php file so  normally all my resources should appears.
In your example I don't see other place where I should declare your resources. 

Regards

**Comment by ferdiunal** [comment]
It seems that the user you're logged in as has permissions for '**Users**' and '**Shield**'. However, after adding a new resource, there might be issues because the resource doesn't have a policy. To fix this, **two commands** need to be added to the package: the first one will create the '**super users**' role, and the second will update the '**super users**' permissions. I'll try to implement these commands when I have time.

**Comment by ferdiunal** [comment]
> Hi,
> 
> I've added "use PermissionAuthorizable" to my app/Nova/Resource.php file so normally all my resources should appears. In your example I don't see other place where I should declare your resources.
> 
> Regards

As a temporary solution, you could avoid assigning a role to the user you're editing. I can't believe I didn't think of that 😅

**Comment by scramatte** [comment]
Hi,

Note that I've already super-admin role , a user assign to it and proper gate to allow everything .
Despite of this I see only  User and Shield resources.   

You talk about policy, do you mean a laravel policy file  in app/Policies ?
Because In my case I've got various resources with their policies. 

I was using another spatie  nova packages  before try yours

Regards

**Comment by scramatte** [comment]
Hi,

I've just forked your repository to take a look in depth to my problem.

I've discovered that  in NovaShield.php ,   app(NovaResources::class)->resources  returns to me only 2 resources:  users and shieldResources

Note that  my resources are located into app/Nova/Resources/[subFolder]/[resourceClass]

I've tried to add resources method in my app/Providers/NovaServiceProvider but it hasn't change anything.

```php
local.INFO: array (
  0 => 
  array (
    'name' => 'Users',
    'prefix' => 
    \Illuminate\Support\Stringable::__set_state(array(
       'value' => 'users::',
    )),
    'policies' => 
    array (
      0 => 'users::viewAny',
      1 => 'users::view',
      2 => 'users::create',
      3 => 'users::update',
      4 => 'users::replicate',
      5 => 'users::delete',
      6 => 'users::restore',
      7 => 'users::forceDelete',
      8 => 'users::runAction',
      9 => 'users::runDestructiveAction',
      10 => 'users::canImpersonate',
      11 => 'users::canBeImpersonated',
      12 => 'users::addUser',
      13 => 'users::attachUser',
      14 => 'users::attachAnyUser',
      15 => 'users::detachUser',
    ),
  ),
  1 => 
  array (
    'name' => 'Shield Resources',
    'prefix' => 
    \Illuminate\Support\Stringable::__set_state(array(
       'value' => 'shieldResources::',
    )),
    'policies' => 
    array (
      0 => 'shieldResources::viewAny',
      1 => 'shieldResources::view',
      2 => 'shieldResources::create',
      3 => 'shieldResources::update',
      4 => 'shieldResources::replicate',
      5 => 'shieldResources::delete',
      6 => 'shieldResources::restore',
      7 => 'shieldResources::forceDelete',
      8 => 'shieldResources::runAction',
      9 => 'shieldResources::runDestructiveAction',
      10 => 'shieldResources::canImpersonate',
      11 => 'shieldResources::canBeImpersonated',
      12 => 'shieldResources::addRole',
      13 => 'shieldResources::attachRole',
      14 => 'shieldResources::attachAnyRole',
      15 => 'shieldResources::detachRole',
    ),
  ),
)  

```

**Comment by scramatte** [comment]
I've just see that  I'm add  my resources path in the config file ...
Now it works, but  I need a way to register  my resources automatically without editing your config file.
Can you fix  the method to look recursively  in subfolders ?

**Comment by ferdiunal** [comment]
> It seems that the user you're logged in as has permissions for '**Users**' and '**Shield**'. However, after adding a new resource, there might be issues because the resource doesn't have a policy. To fix this, **two commands** need to be added to the package: the first one will create the '**super users**' role, and the second will update the '**super users**' permissions. I'll try to implement these commands when I have time.

Hi, I have added the feature I mentioned here. I have added how to use it in the readme. 

--- 

> Hi,
> 
> I've just forked your repository to take a look in depth to my problem.
> 
> I've discovered that in NovaShield.php , app(NovaResources::class)->resources returns to me only 2 resources: users and shieldResources
> 
> Note that my resources are located into app/Nova/Resources/[subFolder]/[resourceClass]
> 
> I've tried to add resources method in my app/Providers/NovaServiceProvider but it hasn't change anything.

You can add your Nova resources in different paths as in the example below.

```php
return [
    'resources' => [
        app_path('Nova'),
        app_path('Nova/Sub'),
    ]
]
```
---- 
> I've just see that I'm add my resources path in the config file ... Now it works, but I need a way to register my resources automatically without editing your config file. Can you fix the method to look recursively in subfolders ?

It is possible to add all Nova Resources, maybe it can be added in the future.
