### ISSUE TITLE
Feature Requests:  Group permissions card per module

### ISSUE THREAD

**Issue by scramatte** [ferdiunal/nova-shield#5]
Hi,

My app has lot of modules. I would like to have something to group permissions by module

For example:  Crm/Contact -> crm.contacts::viewAny ...

Ideally the permissions card will be displayed grouped by module : billing, crm, assets, ... 
with search field  that will search into module, resource and permission

Regards

**Comment by ferdiunal** [comment]
Search may be added, but I don't know how necessary grouping is.

**Comment by scramatte** [comment]
Grouping is because at least in my case I've got  a complete ERP with dozens of modules:
Billing, Crm, Assets, Provisioning, Telephony, Wharehouse, Tickets,  Settings, Common Data, ...
and sometimes resources can have same name in different module.

**Comment by ferdiunal** [comment]
> Grouping is because at least in my case I've got a complete ERP with dozens of modules:
> Billing, Crm, Assets, Provisioning, Telephony, Wharehouse, Tickets, Settings, Common Data, ...
> and sometimes resources can have same name in different module.

I understand, and while the project is open source, I believe that the project will be better by contributing by adding this feature.
